"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { api, ApiError } from "@/lib/api";
import { Badge, type BadgeTone } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Callout } from "@/components/ui/Callout";
import { DataTable } from "@/components/ui/Table";
import { Field, InlineError, Metric, MetricStrip, SelectInput, TextArea, TextInput } from "./Primitives";
import { useActor } from "@/components/identity/ActorContext";
import type { Deal, DealMilestone, DealStage, DealTask, DealWorkstream, DiligenceRequestRecord, LedgerEntry, StageGate, TeamMember, WorkflowActor, WorkflowAuditEvent } from "@/lib/types";

const stages: DealStage[] = ["sourcing", "screening", "initial_review", "diligence", "ic_review", "signing", "closed", "declined"];
const title = (x: string) => x.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
const badgeTone = (status: string): BadgeTone => ["complete", "accepted", "satisfied", "validated", "resolved"].includes(status) ? "green" : ["blocked", "rejected", "declined"].includes(status) ? "red" : ["in_progress", "requested", "responded", "under_review"].includes(status) ? "amber" : "slate";

export function ExecutionWorkbench({ initialDeal }: { workspaceId: string; initialDeal: Deal }) {
  const { actor, profile } = useActor();
  const [deal, setDeal] = useState(initialDeal); const [workstreams, setWorkstreams] = useState<DealWorkstream[]>([]); const [milestones, setMilestones] = useState<DealMilestone[]>([]); const [tasks, setTasks] = useState<DealTask[]>([]); const [requests, setRequests] = useState<DiligenceRequestRecord[]>([]); const [ledger, setLedger] = useState<LedgerEntry[]>([]); const [gates, setGates] = useState<StageGate[]>([]); const [team, setTeam] = useState<TeamMember[]>([]); const [audit, setAudit] = useState<WorkflowAuditEvent[]>([]);
  const [tab, setTab] = useState<"plan" | "requests" | "ledger" | "governance">("plan"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const ctx = useMemo(() => ({ ...actor, organizationId: deal.organization_id }), [actor, deal.organization_id]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [d, ws, ms, ts, rs, le, gs, tm, au] = await Promise.all([api.getDeal(deal.id, ctx), api.listWorkstreams(deal.id, ctx), api.listMilestones(deal.id, ctx), api.listTasks(deal.id, ctx), api.listDiligenceRequests(deal.id, ctx), api.listLedger(deal.id, ctx), api.listGates(deal.id, ctx), api.listTeam(deal.id, ctx), api.listWorkflowAudit(deal.id, ctx)]); setDeal(d); setWorkstreams(ws); setMilestones(ms); setTasks(ts); setRequests(rs); setLedger(le); setGates(gs); setTeam(tm); setAudit(au); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not load deal execution data."); } finally { setLoading(false); } }, [ctx, deal.id]);
  useEffect(() => { void load(); }, [load]);
  const doneTasks = tasks.filter((x) => x.status === "complete").length; const openRequests = requests.filter((x) => !["accepted", "closed"].includes(x.status)).length; const blockingGates = gates.filter((x) => x.required && x.status === "pending" && x.stage === deal.stage).length; const openRisks = ledger.filter((x) => x.entry_type === "risk" && !["resolved", "accepted", "mitigated"].includes(x.status)).length;
  async function mutate(action: () => Promise<unknown>) { setError(null); try { await action(); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : "Action failed."); } }
  async function transition(stage: DealStage) { if (stage !== deal.stage) await mutate(() => api.transitionDeal(deal.id, stage, "Stage transition recorded in the execution workbench", ctx)); }
  return <div className="space-y-6">
    <Card><div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-semibold text-accent">{deal.code}</span><Badge tone="indigo">{title(deal.stage)}</Badge><Badge tone={deal.status === "active" ? "green" : "amber"}>{deal.status}</Badge></div><h2 className="mt-2 font-serif text-2xl font-semibold text-ink">{deal.target_company}</h2><p className="mt-1 max-w-3xl text-sm leading-relaxed text-muted">{deal.summary || "No transaction summary has been recorded."}</p></div><Field label="Stage gate"><SelectInput value={deal.stage} onChange={(e) => void transition(e.target.value as DealStage)}>{stages.map((x) => <option key={x} value={x}>{title(x)}</option>)}</SelectInput></Field></div></Card>
    <MetricStrip columns={5}><Metric label="Workstreams" value={workstreams.length} detail={`${workstreams.filter((x) => x.status === "complete").length} complete`} /><Metric label="Tasks" value={`${doneTasks}/${tasks.length}`} detail="Completed" /><Metric label="Open requests" value={openRequests} tone={openRequests ? "warning" : "positive"} /><Metric label="Open risks" value={openRisks} tone={openRisks ? "negative" : "positive"} /><Metric label="Blocking gates" value={blockingGates} detail={`Current: ${title(deal.stage)}`} tone={blockingGates ? "negative" : "positive"} /></MetricStrip>
    <div className="flex flex-wrap items-center justify-between gap-3"><InlineError message={error} /><p className="text-2xs text-faint">Workflow actions are signed as <strong className="text-body">{profile.name}</strong>. Switch identity in the header for independent review.</p></div>
    <div className="flex overflow-x-auto border-b border-line">{([ ["plan", "Workplan"], ["requests", "Request list"], ["ledger", "Thesis & issues"], ["governance", "Team & gates"] ] as const).map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`whitespace-nowrap border-b-2 px-4 py-2 text-xs font-semibold ${tab === key ? "border-accent text-accent" : "border-transparent text-muted hover:text-ink"}`}>{label}</button>)}</div>
    {tab === "plan" && <PlanPanel deal={deal} workstreams={workstreams} milestones={milestones} tasks={tasks} mutate={mutate} ctx={ctx} />}
    {tab === "requests" && <RequestsPanel deal={deal} workstreams={workstreams} requests={requests} mutate={mutate} ctx={ctx} />}
    {tab === "ledger" && <LedgerPanel deal={deal} ledger={ledger} mutate={mutate} ctx={ctx} />}
    {tab === "governance" && <GovernancePanel deal={deal} gates={gates} team={team} audit={audit} mutate={mutate} ctx={ctx} />}
    {loading && <p className="text-center text-xs text-muted">Refreshing deal controls…</p>}
  </div>;
}

type Ctx = WorkflowActor & { organizationId: string };
type Mutate = (action: () => Promise<unknown>) => Promise<void>;
function PlanPanel({ deal, workstreams, milestones, tasks, mutate, ctx }: { deal: Deal; workstreams: DealWorkstream[]; milestones: DealMilestone[]; tasks: DealTask[]; mutate: Mutate; ctx: Ctx }) {
  async function addWorkstream(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = e.currentTarget; const d = new FormData(f); await mutate(() => api.createWorkstream(deal.id, { slug: String(d.get("slug")), label: String(d.get("label")), description: String(d.get("description")), lead_actor_id: String(d.get("lead")) || null, due_date: String(d.get("due_date")) || null }, ctx)); f.reset(); }
  async function addTask(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = e.currentTarget; const d = new FormData(f); await mutate(() => api.createTask(deal.id, { workstream_id: String(d.get("workstream_id")) || null, title: String(d.get("title")), description: String(d.get("description")), priority: String(d.get("priority")), assignee_actor_id: String(d.get("assignee")) || null, due_date: String(d.get("due_date")) || null, dependency_task_ids: [] }, ctx)); f.reset(); }
  async function addMilestone(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = e.currentTarget; const d = new FormData(f); await mutate(() => api.createMilestone(deal.id, { workstream_id: String(d.get("workstream_id")) || null, title: String(d.get("title")), due_date: String(d.get("due_date")) || null }, ctx)); f.reset(); }
  return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{workstreams.map((ws) => { const own = tasks.filter((x) => x.workstream_id === ws.id); const done = own.filter((x) => x.status === "complete").length; return <Card key={ws.id} eyebrow={title(ws.status)} title={ws.label} subtitle={ws.due_date ? `Due ${ws.due_date}` : "No due date"}><p className="text-xs leading-relaxed text-muted">{ws.description || "No scope description."}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-sunken"><div className="h-full bg-accent" style={{ width: `${own.length ? done / own.length * 100 : 0}%` }} /></div><div className="mt-1.5 flex justify-between text-2xs text-faint"><span>{done} of {own.length} tasks</span><span>{ws.lead_actor_id ?? "Unassigned"}</span></div></Card>; })}{!workstreams.length && <div className="md:col-span-2 xl:col-span-3"><Callout tone="muted">Create workstreams to structure ownership, deadlines, and completion controls.</Callout></div>}</div>
    <div className="grid gap-6 xl:grid-cols-2"><Card eyebrow="Execution queue" title="Tasks"><DataTable rows={tasks} getRowKey={(x) => x.id} empty="No execution tasks." columns={[{ key: "title", header: "Task", render: (x) => <div><div className="font-medium text-ink">{x.title}</div><div className="text-2xs text-faint">{workstreams.find((w) => w.id === x.workstream_id)?.label ?? "General"}</div></div> }, { key: "owner", header: "Assignee", render: (x) => x.assignee_actor_id ?? "—" }, { key: "due", header: "Due", render: (x) => x.due_date ?? "—" }, { key: "priority", header: "Priority", render: (x) => <Badge tone={x.priority === "critical" || x.priority === "high" ? "red" : "slate"}>{x.priority}</Badge> }, { key: "status", header: "Status", render: (x) => <select value={x.status} onChange={(e) => void mutate(() => api.updateTask(x.id, { status: e.target.value, blocked_reason: e.target.value === "blocked" ? "Blocked in execution workbench" : null }, ctx))} className="rounded border border-line bg-panel2 px-2 py-1 text-2xs"><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="complete">Complete</option><option value="cancelled">Cancelled</option></select> }]} /></Card><Card eyebrow="Stage plan" title="Milestones"><DataTable rows={milestones} getRowKey={(x) => x.id} empty="No milestones." columns={[{ key: "title", header: "Milestone", render: (x) => x.title }, { key: "due", header: "Due", render: (x) => x.due_date ?? "—" }, { key: "status", header: "Status", render: (x) => <select value={x.status} onChange={(e) => void mutate(() => api.updateMilestone(x.id, { status: e.target.value }, ctx))} className="rounded border border-line bg-panel2 px-2 py-1 text-2xs"><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="complete">Complete</option></select> }]} /></Card></div>
    <div className="grid gap-6 xl:grid-cols-3"><Card eyebrow="New" title="Workstream"><form onSubmit={addWorkstream} className="space-y-3"><Field label="Label"><TextInput name="label" required placeholder="Commercial diligence" /></Field><Field label="Slug"><TextInput name="slug" required pattern="[a-z0-9_]+" placeholder="commercial" /></Field><Field label="Lead"><TextInput name="lead" placeholder="Actor ID" /></Field><Field label="Due"><TextInput name="due_date" type="date" /></Field><Field label="Scope"><TextArea name="description" rows={2} /></Field><Button type="submit">Add workstream</Button></form></Card><Card eyebrow="New" title="Task"><form onSubmit={addTask} className="space-y-3"><Field label="Title"><TextInput name="title" required /></Field><Field label="Workstream"><SelectInput name="workstream_id"><option value="">General</option>{workstreams.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</SelectInput></Field><div className="grid grid-cols-2 gap-3"><Field label="Priority"><SelectInput name="priority"><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option><option value="low">Low</option></SelectInput></Field><Field label="Due"><TextInput name="due_date" type="date" /></Field></div><Field label="Assignee"><TextInput name="assignee" placeholder="Actor ID" /></Field><Field label="Description"><TextArea name="description" rows={2} /></Field><Button type="submit">Add task</Button></form></Card><Card eyebrow="New" title="Milestone"><form onSubmit={addMilestone} className="space-y-3"><Field label="Title"><TextInput name="title" required /></Field><Field label="Workstream"><SelectInput name="workstream_id"><option value="">General</option>{workstreams.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</SelectInput></Field><Field label="Due"><TextInput name="due_date" type="date" /></Field><Button type="submit">Add milestone</Button></form></Card></div>
  </div>;
}

function RequestsPanel({ deal, workstreams, requests, mutate, ctx }: { deal: Deal; workstreams: DealWorkstream[]; requests: DiligenceRequestRecord[]; mutate: Mutate; ctx: Ctx }) {
  async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f=e.currentTarget; const d=new FormData(f); await mutate(() => api.createDiligenceRequest(deal.id, { workstream_id: String(d.get("workstream_id")) || null, title: String(d.get("title")), question: String(d.get("question")), rationale: String(d.get("rationale")), priority: String(d.get("priority")), owner_actor_id: String(d.get("owner")) || null, respondent_actor_id: String(d.get("respondent")) || null, due_date: String(d.get("due_date")) || null, send_now: d.get("send_now") === "on" }, ctx)); f.reset(); }
  return <div className="space-y-6"><Card eyebrow="Management request list" title="Diligence requests"><DataTable rows={requests} getRowKey={(x)=>x.id} empty="No diligence requests." columns={[{key:"num",header:"#",render:(x)=>x.request_number},{key:"request",header:"Request",render:(x)=><div className="max-w-md"><div className="font-medium text-ink">{x.title}</div><div className="mt-0.5 line-clamp-2 text-2xs text-muted">{x.question}</div></div>},{key:"owner",header:"Owner / respondent",render:(x)=><div className="text-2xs"><div>{x.owner_actor_id ?? "Unassigned"}</div><div className="text-faint">{x.respondent_actor_id ?? "No respondent"}</div></div>},{key:"due",header:"Due",render:(x)=>x.due_date ?? "—"},{key:"status",header:"Status",render:(x)=><Badge tone={badgeTone(x.status)}>{title(x.status)}</Badge>},{key:"actions",header:"Actions",render:(x)=><div className="flex flex-wrap gap-1">{x.status === "draft" && <Button variant="ghost" onClick={()=>void mutate(()=>api.sendDiligenceRequest(x.id,ctx))}>Send</Button>}{["responded","under_review"].includes(x.status) && <><Button variant="ghost" onClick={()=>void mutate(()=>api.reviewDiligenceRequest(x.id,"accept","Accepted by deal team",ctx))}>Accept</Button><Button variant="ghost" onClick={()=>void mutate(()=>api.reviewDiligenceRequest(x.id,"reject","Response is incomplete",ctx))}>Reject</Button></>}</div>}]} /></Card><Card eyebrow="New request" title="Add to the diligence list"><form onSubmit={create} className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Field label="Title" className="lg:col-span-2"><TextInput name="title" required /></Field><Field label="Workstream"><SelectInput name="workstream_id"><option value="">General</option>{workstreams.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</SelectInput></Field><Field label="Priority"><SelectInput name="priority"><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option><option value="low">Low</option></SelectInput></Field><Field label="Question" className="md:col-span-2"><TextArea name="question" required rows={3} /></Field><Field label="Rationale" className="md:col-span-2"><TextArea name="rationale" rows={3} /></Field><Field label="Owner"><TextInput name="owner" placeholder="Actor ID" /></Field><Field label="Respondent"><TextInput name="respondent" placeholder="Actor ID" /></Field><Field label="Due"><TextInput name="due_date" type="date" /></Field><label className="flex items-center gap-2 self-end pb-2 text-xs"><input name="send_now" type="checkbox" className="accent-accent" /> Send immediately</label><div className="md:col-span-2 lg:col-span-4"><Button type="submit">Create request</Button></div></form></Card>{requests.filter(x=>x.status==="requested").map(x=><ResponseForm key={x.id} request={x} mutate={mutate} ctx={ctx} />)}</div>;
}
function ResponseForm({request,mutate,ctx}:{request:DiligenceRequestRecord;mutate:Mutate;ctx:Ctx}) { async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const d=new FormData(f);await mutate(()=>api.respondToDiligenceRequest(request.id,String(d.get("response_text")),ctx));f.reset();} return <Card eyebrow={`Request ${request.request_number}`} title={`Record response · ${request.title}`}><form onSubmit={submit} className="flex flex-col gap-3 sm:flex-row sm:items-end"><Field label="Management response" className="flex-1"><TextArea name="response_text" rows={2} required /></Field><Button type="submit">Record response</Button></form></Card> }

function LedgerPanel({deal,ledger,mutate,ctx}:{deal:Deal;ledger:LedgerEntry[];mutate:Mutate;ctx:Ctx}) { async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const d=new FormData(f);await mutate(()=>api.createLedgerEntry(deal.id,{entry_type:String(d.get("entry_type")) as "thesis"|"issue"|"risk"|"decision",title:String(d.get("title")),description:String(d.get("description")),severity:String(d.get("severity")),status:"open",evidence_refs:String(d.get("evidence_refs")||"").split(",").map(x=>x.trim()).filter(Boolean),related_artifact_ids:[]},ctx));f.reset();} return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-2">{ledger.map(x=><Card key={x.id} eyebrow={`${title(x.entry_type)} · v${x.version}`} title={x.title} right={<Badge tone={badgeTone(x.status)}>{x.status}</Badge>}><p className="text-xs leading-relaxed text-muted">{x.description}</p><div className="mt-3 flex flex-wrap gap-1">{x.evidence_refs.map(ref=><Badge key={ref} tone="indigo">{ref}</Badge>)}<Badge tone={x.severity==="high"||x.severity==="critical"?"red":"slate"}>{x.severity}</Badge></div></Card>)}</div>{!ledger.length&&<Callout tone="muted">The decision ledger is empty. Record the investment thesis, issues, risks, and explicit decisions as diligence evolves.</Callout>}<Card eyebrow="Decision record" title="Add ledger entry"><form onSubmit={create} className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Field label="Type"><SelectInput name="entry_type"><option value="thesis">Thesis</option><option value="issue">Issue</option><option value="risk">Risk</option><option value="decision">Decision</option></SelectInput></Field><Field label="Severity"><SelectInput name="severity"><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option><option value="low">Low</option></SelectInput></Field><Field label="Title" className="lg:col-span-2"><TextInput name="title" required /></Field><Field label="Description" className="md:col-span-2 lg:col-span-3"><TextArea name="description" required rows={3} /></Field><Field label="Evidence refs"><TextInput name="evidence_refs" placeholder="E-014, E-027" /></Field><div className="md:col-span-2 lg:col-span-4"><Button type="submit">Add entry</Button></div></form></Card></div> }

function GovernancePanel({deal,gates,team,audit,mutate,ctx}:{deal:Deal;gates:StageGate[];team:TeamMember[];audit:WorkflowAuditEvent[];mutate:Mutate;ctx:Ctx}) { async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const d=new FormData(f);await mutate(()=>api.addTeamMember(deal.id,{actor_id:String(d.get("actor_id")),display_name:String(d.get("display_name")),email:String(d.get("email"))||null,role:String(d.get("role"))},ctx));f.reset();} return <div className="grid gap-6 xl:grid-cols-2"><Card eyebrow="Stage governance" title="Required gates"><DataTable rows={gates} getRowKey={x=>x.id} empty="No stage gates." columns={[{key:"gate",header:"Gate",render:x=><div><div className="font-medium text-ink">{x.label}</div><div className="text-2xs text-faint">{title(x.stage)}</div></div>},{key:"required",header:"Required",render:x=>x.required?"Yes":"No"},{key:"status",header:"Status",render:x=><Badge tone={badgeTone(x.status)}>{x.status}</Badge>},{key:"action",header:"Action",render:x=>x.status==="pending"?<Button variant="ghost" onClick={()=>void mutate(()=>api.resolveGate(x.id,"satisfied","Reviewed and satisfied",ctx))}>Satisfy</Button>:null}]} /></Card><Card eyebrow="Deal team" title="Ownership"><DataTable rows={team} getRowKey={x=>x.id} empty="No team members." columns={[{key:"name",header:"Name",render:x=><div><div className="font-medium text-ink">{x.display_name}</div><div className="text-2xs text-faint">{x.email}</div></div>},{key:"role",header:"Role",render:x=><Badge tone="slate">{title(x.role)}</Badge>}]} /><form onSubmit={add} className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Display name"><TextInput name="display_name" required /></Field><Field label="Actor ID"><TextInput name="actor_id" required /></Field><Field label="Email"><TextInput name="email" type="email" /></Field><Field label="Role"><SelectInput name="role"><option value="deal_lead">Deal lead</option><option value="investment_partner">Investment partner</option><option value="principal">Principal</option><option value="associate">Associate</option><option value="operating_partner">Operating partner</option><option value="finance">Finance</option><option value="legal">Legal</option><option value="advisor">Advisor</option></SelectInput></Field><div className="sm:col-span-2"><Button type="submit">Add team member</Button></div></form></Card><Card eyebrow="Audit trail" title="Recent workflow events" className="xl:col-span-2"><DataTable rows={audit.slice(0,30)} getRowKey={x=>x.id} empty="No audit events." columns={[{key:"at",header:"Time",render:x=>x.created_at.slice(0,16).replace("T"," ")},{key:"actor",header:"Actor",render:x=>x.actor_display_name??x.actor_id??"System"},{key:"action",header:"Action",render:x=><span className="font-mono text-2xs">{x.action}</span>},{key:"entity",header:"Entity",render:x=>`${title(x.entity_type)} · ${x.entity_id.slice(0,8)}`}]} /></Card></div> }
