"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { FormEvent } from "react";
import { api, ApiError } from "@/lib/api";
import { Badge, type BadgeTone } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Callout } from "@/components/ui/Callout";
import { DataTable } from "@/components/ui/Table";
import { EmptyPanel, Field, InlineError, Metric, MetricStrip, SelectInput, TextArea, TextInput } from "./Primitives";
import { useActor } from "@/components/identity/ActorContext";
import type { CitedQARun, ClaimCategory, ClaimCollection, DataRoomDocument, Deal, DocumentComparison, IntelligenceEvaluation, StructuredClaim, WorkflowActor } from "@/lib/types";

const tone = (status: string): BadgeTone => status === "approved" || status === "answered" ? "green" : status === "rejected" || status === "abstained" ? "red" : "amber";
const title = (x: string) => x.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());

export function IntelligenceWorkbench({ deal }: { deal: Deal }) {
  const { actor, profile } = useActor();
  const ctx = useMemo(() => ({ ...actor, organizationId: deal.organization_id }), [actor, deal.organization_id]); const [documents, setDocuments] = useState<DataRoomDocument[]>([]); const [qaRuns, setQaRuns] = useState<CitedQARun[]>([]); const [claims, setClaims] = useState<ClaimCollection>({ approved: [], pending: [], rejected: [], counts: {} }); const [comparisons, setComparisons] = useState<DocumentComparison[]>([]); const [evaluations, setEvaluations] = useState<IntelligenceEvaluation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [tab, setTab] = useState<"qa" | "claims" | "compare" | "documents">("qa");
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [d,q,c,co,e] = await Promise.all([api.listIntelligenceDocuments(deal.id,ctx),api.listQARuns(deal.id,ctx),api.getClaims(deal.id,ctx),api.listIntelligenceComparisons(deal.id,ctx),api.listIntelligenceEvaluations(deal.id,ctx)]); setDocuments(d); setQaRuns(q); setClaims(c); setComparisons(co); setEvaluations(e); } catch(e) { setError(e instanceof ApiError?e.message:"Could not load deal intelligence."); } finally { setLoading(false); } }, [ctx, deal.id]);
  useEffect(()=>{void load();},[load]);
  // Returns whether the action succeeded so forms only clear the analyst's input on success.
  async function mutate(action:()=>Promise<unknown>){setError(null);try{await action();await load();return true;}catch(e){setError(e instanceof ApiError?e.message:"Action failed.");return false;}}
  return <div className="space-y-6"><MetricStrip columns={5}><Metric label="Documents" value={documents.length} detail="Latest versions" /><Metric label="Cited answers" value={qaRuns.filter(x=>x.status==="answered").length} /><Metric label="Abstentions" value={qaRuns.filter(x=>x.status==="abstained").length} tone={qaRuns.some(x=>x.status==="abstained")?"warning":"default"} /><Metric label="Claims pending" value={claims.pending.length} tone={claims.pending.length?"warning":"positive"} /><Metric label="Approved claims" value={claims.approved.length} tone="positive" /></MetricStrip><div className="flex flex-wrap items-center justify-between gap-3"><InlineError message={error}/><p className="text-2xs text-faint">Extraction and claim decisions record <strong className="text-body">{profile.name}</strong>.</p></div><div className="flex overflow-x-auto border-b border-line">{([ ["qa","Cited Q&A"],["claims","Extraction & review"],["compare","Contradictions"],["documents","Documents"] ] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`whitespace-nowrap border-b-2 px-4 py-2 text-xs font-semibold ${tab===k?"border-accent text-accent":"border-transparent text-muted hover:text-ink"}`}>{l}</button>)}</div>{tab==="qa"&&<QAPanel deal={deal} documents={documents} runs={qaRuns} mutate={mutate} ctx={ctx}/>} {tab==="claims"&&<ClaimsPanel deal={deal} documents={documents} claims={claims} mutate={mutate} ctx={ctx}/>} {tab==="compare"&&<ComparePanel deal={deal} documents={documents} comparisons={comparisons} mutate={mutate} ctx={ctx}/>} {tab==="documents"&&<DocumentsPanel deal={deal} documents={documents} mutate={mutate} ctx={ctx}/>} {loading&&<p className="text-center text-xs text-muted">Refreshing evidence controls…</p>}{evaluations[0]&&<Callout tone={evaluations[0].passed?"info":"warning"} title="Latest intelligence evaluation">Guardrail suite {evaluations[0].passed?"passed":"requires attention"}. Algorithm {evaluations[0].algorithm_version}; run {evaluations[0].created_at.slice(0,10)}.</Callout>}</div>;
}
type Ctx=WorkflowActor&{organizationId:string}; type Mutate=(a:()=>Promise<unknown>)=>Promise<boolean>;
function QAPanel({deal,documents,runs,mutate,ctx}:{deal:Deal;documents:DataRoomDocument[];runs:CitedQARun[];mutate:Mutate;ctx:Ctx}) { const [answer,setAnswer]=useState<CitedQARun|null>(null);const [busy,setBusy]=useState(false);
  // The QA call runs INSIDE mutate so a backend failure surfaces through the shared error state
  // instead of vanishing as an unhandled rejection.
  async function ask(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);try{await mutate(async()=>{const result=await api.askDealRoom(deal.id,String(d.get("question")),d.getAll("document_id").map(String),ctx);setAnswer(result);});}finally{setBusy(false);}}const shown=answer??runs[0]??null;return <div className="space-y-6"><Card eyebrow="Evidence query" title="Ask the deal room" subtitle="Answers either cite exact immutable document spans or abstain."><form onSubmit={ask} className="space-y-3"><Field label="Question"><TextArea name="question" rows={3} required placeholder="What is the maximum total leverage covenant, and when does it step down?" /></Field>{documents.length>0&&<details><summary className="cursor-pointer text-xs font-semibold text-accent">Limit to selected documents</summary><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{documents.map(x=><label key={x.id} className="flex items-center gap-2 rounded border border-line bg-panel2 px-3 py-2 text-xs"><input type="checkbox" name="document_id" value={x.id} className="accent-accent"/><span className="truncate">{x.title}</span></label>)}</div></details>}<Button type="submit" disabled={busy||!documents.length}>{busy?"Retrieving evidence…":"Ask with citations"}</Button></form></Card>{shown&&<Card eyebrow="Cited answer" title={shown.question} right={<Badge tone={tone(shown.status)}>{shown.status}</Badge>}><div className="whitespace-pre-wrap text-sm leading-relaxed text-body">{shown.answer||"No supported answer was found in the selected corpus."}</div>{shown.citations.length>0&&<div className="mt-5 space-y-3"><div className="text-2xs font-semibold uppercase tracking-eyebrow text-muted">Source spans</div>{shown.citations.map((c,i)=><blockquote key={`${c.chunk_id}-${i}`} className="border-l-2 border-accent bg-panel2 px-4 py-3"><p className="text-xs leading-relaxed text-body">“{c.quote}”</p><footer className="mt-2 flex flex-wrap gap-2 text-2xs text-faint"><span className="font-semibold text-accent">{c.filename} · v{c.document_version}</span><span>{JSON.stringify(c.locator)}</span><span className="font-mono">{c.content_hash.slice(0,10)}…</span></footer></blockquote>)}</div>}<div className="mt-4 text-2xs text-faint">Answer hash {shown.answer_hash} · {shown.algorithm_version}</div></Card>}{!shown&&<EmptyPanel title="No questions asked" body="Upload a document, then ask a specific factual or numerical question. Unsupported questions will explicitly abstain."/>}</div> }
function ClaimsPanel({deal,documents,claims,mutate,ctx}:{deal:Deal;documents:DataRoomDocument[];claims:ClaimCollection;mutate:Mutate;ctx:Ctx}) { const cats:ClaimCategory[]=["debt_term","customer","contract","kpi","qoe_candidate"];async function extract(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await mutate(()=>api.extractClaims(deal.id,d.getAll("document_id").map(String),d.getAll("category") as ClaimCategory[],ctx));}const rows=[...claims.pending,...claims.approved,...claims.rejected];return <div className="space-y-6"><Card eyebrow="Structured extraction" title="Extract reviewable claims"><form onSubmit={extract} className="space-y-3"><div className="grid gap-3 lg:grid-cols-2"><Field label="Documents"><div className="max-h-36 space-y-1 overflow-y-auto rounded border border-line p-2">{documents.map(x=><label key={x.id} className="flex items-center gap-2 px-1 py-1 text-xs"><input name="document_id" value={x.id} type="checkbox" className="accent-accent"/><span className="truncate">{x.title} · v{x.version}</span></label>)}</div></Field><Field label="Categories"><div className="grid grid-cols-2 gap-2 rounded border border-line p-3">{cats.map(x=><label key={x} className="flex items-center gap-2 text-xs"><input name="category" value={x} type="checkbox" defaultChecked className="accent-accent"/>{title(x)}</label>)}</div></Field></div><Button type="submit" disabled={!documents.length}>Run schema extraction</Button></form></Card><Card eyebrow="Human claim review" title="Claim ledger" subtitle="Only approved claims are eligible to flow into models or IC artifacts. Extraction authors must switch identity before approving their own claims."><DataTable rows={rows} getRowKey={x=>x.id} empty="No extracted claims." columns={[{key:"claim",header:"Claim",render:x=><div className="max-w-sm"><div className="font-medium text-ink">{title(x.field_name)}</div><div className="mt-0.5 text-xs text-body">{x.value_text}</div><div className="mt-1 font-mono text-2xs text-faint">{JSON.stringify(x.source_locator)}</div></div>},{key:"category",header:"Category",render:x=><Badge tone="indigo">{title(x.category)}</Badge>},{key:"period",header:"Period",render:x=>x.period??"—"},{key:"confidence",header:"Confidence",align:"right",render:x=>`${(x.confidence*100).toFixed(0)}%`},{key:"status",header:"Review",render:x=><Badge tone={tone(x.review_status)}>{x.review_status}</Badge>},{key:"actions",header:"Decision",render:x=><ClaimReviewActions claim={x} mutate={mutate} ctx={ctx}/>}]} /></Card></div> }

function ClaimReviewActions({claim,mutate,ctx}:{claim:StructuredClaim;mutate:Mutate;ctx:Ctx}) {
  if (claim.review_status !== "unreviewed") return <span className="text-2xs text-muted">Revision {claim.revision}</span>;
  const sameActor = Boolean(claim.created_by_actor_id && claim.created_by_actor_id === ctx.actorId);
  if (sameActor) return <span className="text-2xs font-medium text-warn" title="Switch identity in the header to review">Independent review required</span>;
  return <div className="flex gap-1"><Button variant="ghost" onClick={()=>void mutate(()=>api.reviewClaim(claim.id,claim.revision,"approve","Verified against cited source",ctx))}>Approve</Button><Button variant="ghost" onClick={()=>void mutate(()=>api.reviewClaim(claim.id,claim.revision,"reject","Not accepted for underwriting",ctx))}>Reject</Button></div>;
}
function ComparePanel({deal,documents,comparisons,mutate,ctx}:{deal:Deal;documents:DataRoomDocument[];comparisons:DocumentComparison[];mutate:Mutate;ctx:Ctx}) { async function compare(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await mutate(()=>api.compareIntelligenceDocuments(deal.id,String(d.get("from")),String(d.get("to")),String(d.get("type")) as "change"|"contradiction",ctx));}return <div className="space-y-6"><Card eyebrow="Change control" title="Compare two document versions or sources"><form onSubmit={compare} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[1fr_1fr_.7fr_auto] xl:items-end"><Field label="From"><SelectInput name="from" required><option value="">Select document</option>{documents.map(x=><option key={x.id} value={x.id}>{x.title} · v{x.version}</option>)}</SelectInput></Field><Field label="To"><SelectInput name="to" required><option value="">Select document</option>{documents.map(x=><option key={x.id} value={x.id}>{x.title} · v{x.version}</option>)}</SelectInput></Field><Field label="Comparison"><SelectInput name="type"><option value="change">Version changes</option><option value="contradiction">Contradictions</option></SelectInput></Field><Button type="submit" disabled={documents.length<2}>Compare</Button></form></Card>{comparisons.map(x=><Card key={x.id} eyebrow={`${title(x.comparison_type)} comparison`} title={`${x.finding_count} findings`} subtitle={`${documents.find(d=>d.id===x.from_document_id)?.title??"Source"} → ${documents.find(d=>d.id===x.to_document_id)?.title??"Source"}`}><div className="space-y-3">{x.findings.map((f,i)=><div key={i} className="rounded border border-line bg-panel2 p-3"><div className="flex gap-2"><Badge tone={f.finding_type.includes("contradiction")?"red":"amber"}>{title(f.finding_type)}</Badge><p className="text-xs leading-relaxed text-body">{f.summary}</p></div>{(f.before||f.after)&&<div className="mt-2 grid gap-2 sm:grid-cols-2"><pre className="overflow-auto rounded bg-panel p-2 text-2xs text-muted">{JSON.stringify(f.before,null,2)}</pre><pre className="overflow-auto rounded bg-panel p-2 text-2xs text-muted">{JSON.stringify(f.after,null,2)}</pre></div>}</div>)}</div></Card>)}{!comparisons.length&&<EmptyPanel title="No comparisons run" body="Select two distinct documents to surface changes or potentially contradictory claims."/>}</div> }
function DocumentsPanel({deal,documents,mutate,ctx}:{deal:Deal;documents:DataRoomDocument[];mutate:Mutate;ctx:Ctx}) { const file=useRef<HTMLInputElement>(null);async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=file.current?.files?.[0];if(!f)return;const form=e.currentTarget;const d=new FormData(form);if(await mutate(()=>api.uploadIntelligenceDocument(deal.id,f,{title:String(d.get("title"))||undefined,logicalDocumentId:String(d.get("logical_id"))||undefined},ctx)))form.reset();}return <div className="space-y-6"><Card eyebrow="Deal room" title="Upload an evidence document" subtitle="PDF, DOCX, XLSX, CSV, and text documents are hashed, versioned, and chunked with exact locators."><form onSubmit={upload} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[1fr_1fr_1fr_auto] xl:items-end"><Field label="Title"><TextInput name="title" placeholder="Credit agreement" /></Field><Field label="Logical document ID" hint="For new versions"><TextInput name="logical_id" placeholder="Optional existing logical ID" /></Field><Field label="File"><TextInput ref={file} type="file" required accept=".pdf,.docx,.xlsx,.csv,.txt,.md,.json" /></Field><Button type="submit">Upload & index</Button></form></Card><Card eyebrow="Source manifest" title="Latest document versions"><DataTable rows={documents} getRowKey={x=>x.id} empty="No deal-room documents." columns={[{key:"document",header:"Document",render:x=><div><div className="font-medium text-ink">{x.title}</div><div className="text-2xs text-faint">{x.filename}</div></div>},{key:"type",header:"Type",render:x=><Badge tone="slate">{x.extension||x.content_type}</Badge>},{key:"version",header:"Version",align:"right",render:x=>`v${x.version}`},{key:"size",header:"Size",align:"right",render:x=>`${(x.byte_size/1024).toFixed(1)} KB`},{key:"uploaded",header:"Indexed",render:x=>x.created_at.slice(0,10)},{key:"hash",header:"SHA-256",render:x=><span className="font-mono text-2xs" title={x.sha256}>{x.sha256.slice(0,12)}…</span>}]} /></Card></div> }
