"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import Link from "next/link";
import { api, ApiError } from "@/lib/api";
import { Badge, type BadgeTone } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Callout } from "@/components/ui/Callout";
import { Field, InlineError, Metric, MetricStrip, SelectInput, TextArea, TextInput } from "./Primitives";
import { useActor } from "@/components/identity/ActorContext";
import type { Deal, DealStage, Fund, Organization, Workspace } from "@/lib/types";

const STAGES: DealStage[] = ["sourcing", "screening", "initial_review", "diligence", "ic_review", "signing", "closed", "declined"];
const stageName = (stage: string) => stage.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
const stageTone = (stage: string): BadgeTone => stage === "closed" ? "green" : stage === "declined" ? "red" : stage === "ic_review" || stage === "signing" ? "gold" : "indigo";
export function PipelineBoard() {
  const { actor, profile } = useActor();
  const [organizations, setOrganizations] = useState<Organization[]>([]); const [organizationId, setOrganizationId] = useState("");
  const [funds, setFunds] = useState<Fund[]>([]); const [deals, setDeals] = useState<Deal[]>([]); const [workspaces, setWorkspaces] = useState<Workspace[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const loadOrg = useCallback(async (id: string) => { if (!id) { setFunds([]); setDeals([]); return; } setLoading(true); setError(null); try { const [f, d] = await Promise.all([api.listFunds(id, actor), api.listDeals(id, actor)]); setFunds(f); setDeals(d); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not load the pipeline."); } finally { setLoading(false); } }, [actor]);
  const initialize = useCallback(async () => { setLoading(true); try { const [orgs, ws] = await Promise.all([api.listOrganizations(actor), api.listWorkspaces()]); setOrganizations(orgs); setWorkspaces(ws); const saved = typeof window !== "undefined" ? localStorage.getItem("deallens.organizationId") : null; const next = orgs.some((x) => x.id === saved) ? saved! : orgs[0]?.id ?? ""; setOrganizationId(next); await loadOrg(next); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not load pipeline context."); setLoading(false); } }, [actor, loadOrg]);
  useEffect(() => { void initialize(); }, [initialize]);
  async function chooseOrganization(id: string) { setOrganizationId(id); localStorage.setItem("deallens.organizationId", id); await loadOrg(id); }
  async function createOrganization(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setError(null); try { const org = await api.createOrganization({ name: String(data.get("name")), slug: String(data.get("slug")) }, actor); form.reset(); const all = [...organizations, org]; setOrganizations(all); await chooseOrganization(org.id); } catch (e) { setError(e instanceof ApiError ? e.message : "Organization could not be created."); } }
  async function createFund(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!organizationId) return; const form = event.currentTarget; const data = new FormData(form); setError(null); try { await api.createFund(organizationId, { name: String(data.get("name")), vintage_year: Number(data.get("vintage_year")) || null, strategy: String(data.get("strategy")), base_currency: "USD" }, actor); form.reset(); await loadOrg(organizationId); } catch (e) { setError(e instanceof ApiError ? e.message : "Fund could not be created."); } }
  async function createDeal(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setError(null); try { await api.createDeal(String(data.get("fund_id")), { code: String(data.get("code")), name: String(data.get("name")), target_company: String(data.get("target_company")), deal_type: String(data.get("deal_type")), workspace_id: String(data.get("workspace_id")) || null, ic_date: String(data.get("ic_date")) || null, summary: String(data.get("summary")), seed_default_gates: true }, { ...actor, organizationId }); form.reset(); await loadOrg(organizationId); } catch (e) { setError(e instanceof ApiError ? e.message : "Deal could not be created."); } }
  const active = deals.filter((x) => x.status === "active" && !["closed", "declined"].includes(x.stage)); const nearIC = active.filter((x) => ["diligence", "ic_review", "signing"].includes(x.stage)); const byStage = useMemo(() => Object.fromEntries(STAGES.map((s) => [s, deals.filter((d) => d.stage === s)])) as Record<DealStage, Deal[]>, [deals]);
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-3 rounded-md border border-line bg-panel px-4 py-3"><Field label="Organization" className="w-full sm:w-80"><SelectInput value={organizationId} onChange={(e) => void chooseOrganization(e.target.value)}><option value="">Select organization</option>{organizations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</SelectInput></Field><div className="text-right text-2xs text-faint">Actions record {profile.name} · {profile.roleLabel}</div></div>
    <InlineError message={error} />
    {organizationId && <MetricStrip columns={5}><Metric label="Active deals" value={active.length} /><Metric label="In diligence" value={byStage.diligence.length} /><Metric label="Approaching IC" value={nearIC.length} /><Metric label="IC review" value={byStage.ic_review.length} /><Metric label="Closed / declined" value={byStage.closed.length + byStage.declined.length} /></MetricStrip>}
    {!organizationId ? <Card eyebrow="Firm setup" title="Create the first organization"><form onSubmit={createOrganization} className="grid gap-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><Field label="Organization name"><TextInput name="name" required placeholder="Northbridge Capital" /></Field><Field label="Slug"><TextInput name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="northbridge-capital" /></Field><Button type="submit">Create organization</Button></form></Card> : <>
      <div className="overflow-x-auto pb-2"><div className="grid min-w-[1220px] grid-cols-6 gap-3">{STAGES.filter((x) => !["closed", "declined"].includes(x)).map((stage) => <section key={stage} className="rounded-md border border-line bg-panel2"><div className="flex items-center justify-between border-b border-line px-3 py-2.5"><h2 className="text-2xs font-semibold uppercase tracking-eyebrow text-muted">{stageName(stage)}</h2><span className="rounded-full bg-panel px-2 py-0.5 text-2xs text-muted">{byStage[stage].length}</span></div><div className="space-y-2 p-2">{byStage[stage].map((deal) => <DealCard key={deal.id} deal={deal} onChange={() => loadOrg(organizationId)} />)}{!byStage[stage].length && <div className="px-2 py-6 text-center text-2xs text-faint">No deals</div>}</div></section>)}</div></div>
      <div className="grid gap-6 xl:grid-cols-3"><Card eyebrow="Portfolio setup" title="Add a fund"><form onSubmit={createFund} className="space-y-3"><Field label="Fund name"><TextInput name="name" required placeholder="Fund IV" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Vintage"><TextInput name="vintage_year" type="number" min="1900" max="2200" /></Field><Field label="Strategy"><SelectInput name="strategy"><option value="buyout">Buyout</option><option value="growth_equity">Growth equity</option><option value="private_credit">Private credit</option></SelectInput></Field></div><Button type="submit">Add fund</Button></form></Card><Card eyebrow="Deal intake" title="Add a deal" className="xl:col-span-2"><form onSubmit={createDeal} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="Fund"><SelectInput name="fund_id" required><option value="">Select fund</option>{funds.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</SelectInput></Field><Field label="Deal code"><TextInput name="code" required placeholder="PROJECT ATLAS" /></Field><Field label="Deal name"><TextInput name="name" required placeholder="Project Atlas" /></Field><Field label="Target company"><TextInput name="target_company" required /></Field><Field label="Deal type"><SelectInput name="deal_type"><option value="buyout">Buyout</option><option value="growth_equity">Growth equity</option><option value="private_credit">Private credit</option></SelectInput></Field><Field label="Workspace"><SelectInput name="workspace_id"><option value="">Not connected</option>{workspaces.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</SelectInput></Field><Field label="IC date"><TextInput name="ic_date" type="date" /></Field><Field label="Summary" className="sm:col-span-2"><TextArea name="summary" rows={2} placeholder="Transaction thesis and current process context" /></Field><div className="self-end"><Button type="submit" disabled={!funds.length}>Create deal</Button></div></form></Card></div>
      {!funds.length && <Callout tone="muted" title="Fund required">Add a fund before creating pipeline deals.</Callout>}
    </>}
    {loading && <p className="text-center text-xs text-muted">Refreshing pipeline…</p>}
  </div>;
}

function DealCard({ deal, onChange }: { deal: Deal; onChange: () => Promise<void> }) {
  const { actor } = useActor();
  const [busy, setBusy] = useState(false);
  async function transition(to: DealStage) { if (to === deal.stage) return; setBusy(true); try { await api.transitionDeal(deal.id, to, "Pipeline stage updated", { ...actor, organizationId: deal.organization_id }); await onChange(); } finally { setBusy(false); } }
  return <article className="rounded border border-line bg-panel p-3 shadow-xs"><div className="flex items-start justify-between gap-2"><span className="font-mono text-2xs font-semibold text-accent">{deal.code}</span><Badge tone={stageTone(deal.stage)}>{deal.status}</Badge></div><h3 className="mt-1.5 font-sans text-sm font-semibold leading-snug text-ink">{deal.target_company}</h3><p className="mt-1 line-clamp-2 text-2xs leading-relaxed text-muted">{deal.summary || "No deal summary yet."}</p><div className="mt-3 flex items-end justify-between gap-2"><div className="text-2xs text-faint">{deal.ic_date ? `IC ${deal.ic_date}` : "IC date not set"}</div>{deal.workspace_id && <Link href={`/workspaces/${deal.workspace_id}`} className="text-2xs font-semibold text-accent">Open →</Link>}</div><label className="mt-2 block"><span className="sr-only">Change stage</span><select disabled={busy} value={deal.stage} onChange={(e) => void transition(e.target.value as DealStage)} className="w-full rounded border border-line bg-panel2 px-2 py-1.5 text-2xs text-muted focus:border-accent focus:outline-none">{STAGES.map((x) => <option key={x} value={x}>{stageName(x)}</option>)}</select></label></article>;
}
