"""signed webhook deliveries

Revision ID: 0fcfabe85d5e
Revises: c556b8038088
Create Date: 2026-07-10 09:51:22.689884
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0fcfabe85d5e'
down_revision: str | Sequence[str] | None = 'c556b8038088'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Legacy DealLens processes created tables directly before Alembic was introduced. The initial
    # revision detects that database; preserve already-populated webhook tables rather than trying
    # to create them a second time.
    existing = set(sa.inspect(op.get_bind()).get_table_names())
    webhook_tables = {"webhook_endpoints", "webhook_deliveries"}
    if webhook_tables <= existing:
        return
    if existing & webhook_tables:
        raise RuntimeError(
            "Legacy webhook schema is incomplete; both webhook_endpoints and "
            "webhook_deliveries must exist or both must be absent"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_endpoints',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=False),
    sa.Column('secret_hint', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','disabled')", name='ck_webhook_endpoint_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_webhook_endpoint_org_name')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index('ix_webhook_endpoints_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_organization_id'), ['organization_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('endpoint_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('audit_event_id', sa.String(length=32), nullable=True),
    sa.Column('event_key', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body_excerpt', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued','delivering','succeeded','failed','dead_letter','cancelled')", name='ck_webhook_delivery_status'),
    sa.ForeignKeyConstraint(['audit_event_id'], ['workflow_audit_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'event_key', name='uq_webhook_delivery_event')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_webhook_deliveries_org_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_webhook_deliveries_status_next', ['status', 'next_attempt_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_webhook_deliveries_status_next')
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_organization_id'))
        batch_op.drop_index('ix_webhook_deliveries_org_created')
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_event_type'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_endpoint_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_organization_id'))
        batch_op.drop_index('ix_webhook_endpoints_org_status')

    op.drop_table('webhook_endpoints')
    # ### end Alembic commands ###
