"""initial wave3 schema

Revision ID: c556b8038088
Revises: 
Create Date: 2026-07-10 09:22:58.230356
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from src import models  # noqa: F401 - populate metadata for legacy database upgrades
from src.db.base import Base


revision: str = 'c556b8038088'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Freeze the tables owned by this revision. The legacy upgrade path must not call ``create_all``
# against future metadata, otherwise later revisions would find their tables created too early.
_INITIAL_TABLES = {
    'organizations', 'workspaces', 'account_mappings', 'analysis_runs', 'audit_logs',
    'comparable_companies', 'diligence_plans', 'diligence_questions', 'evidence', 'filings',
    'funds', 'govcon_profiles', 'memos', 'red_team_reports', 'risk_findings', 'targets',
    'underwriting_case_versions', 'artifact_versions', 'deals', 'document_chunks',
    'sec_filing_comparisons', 'source_snapshots', 'underwriting_case_decisions',
    'canonical_financial_facts', 'cited_qa_runs', 'data_room_documents',
    'deal_ledger_entries', 'deal_stage_gates', 'deal_stage_transitions', 'deal_team_members',
    'deal_workstreams', 'financial_reconciliations', 'ic_packets', 'intelligence_evaluations',
    'qoe_adjustments', 'workflow_audit_events', 'data_room_chunks', 'deal_milestones',
    'diligence_requests', 'document_comparisons', 'financial_import_exceptions', 'ic_comments',
    'ic_decisions', 'ic_packet_exports', 'conditions_to_close', 'deal_tasks',
    'diligence_responses', 'structured_claims', 'claim_review_events', 'diligence_attachments',
}


def upgrade() -> None:
    # Earlier DealLens builds created their schema with SQLAlchemy ``create_all`` and therefore have
    # no Alembic version row. If legacy tables are present, create only the missing Wave 3 tables and
    # let Alembic stamp this revision. Fresh databases continue through the explicit migration below.
    bind = op.get_bind()
    existing = set(sa.inspect(bind).get_table_names()) - {"alembic_version"}
    if existing:
        for table in Base.metadata.sorted_tables:
            if table.name in _INITIAL_TABLES:
                table.create(bind=bind, checkfirst=True)
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('external_tenant_id', sa.String(length=200), nullable=True),
    sa.Column('identity_provider', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_tenant_id'),
    sa.UniqueConstraint('slug', name='uq_organizations_slug')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=False)

    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('deal_type', sa.String(length=40), nullable=False),
    sa.Column('investment_question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_mappings',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('raw_account', sa.String(length=240), nullable=False),
    sa.Column('raw_account_normalized', sa.String(length=240), nullable=False),
    sa.Column('canonical_account', sa.String(length=120), nullable=False),
    sa.Column('statement', sa.String(length=30), nullable=False),
    sa.Column('sign_multiplier', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['account_mappings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'source_type', 'raw_account_normalized', 'version', name='uq_account_mapping_version')
    )
    with op.batch_alter_table('account_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_mappings_canonical_account'), ['canonical_account'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_mappings_raw_account_normalized'), ['raw_account_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_mappings_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('run_type', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_snapshot_ids', sa.JSON(), nullable=True),
    sa.Column('input_manifest', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('code_version', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'run_type', 'version', name='uq_analysis_run_type_version')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_run_type'), ['run_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.String(length=32), nullable=True),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('comparable_companies',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('rnd_pct', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('enterprise_value', sa.Float(), nullable=True),
    sa.Column('ev_revenue_multiple', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('data_source', sa.String(length=60), nullable=False),
    sa.Column('is_illustrative', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparable_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparable_companies_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('diligence_plans',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('investment_question', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('workstreams', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('diligence_questions',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('workstream', sa.String(length=40), nullable=False),
    sa.Column('workstream_label', sa.String(length=80), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('evidence_ref', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diligence_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diligence_questions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('evidence',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=20), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_date', sa.String(length=20), nullable=True),
    sa.Column('source_section', sa.Text(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_ref'), ['ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('filings',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.String(length=20), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('local_text_path', sa.Text(), nullable=True),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filings_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('funds',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('strategy', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive','realized')", name='ck_funds_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_funds_org_name')
    )
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funds_organization_id'), ['organization_id'], unique=False)

    op.create_table('govcon_profiles',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('total_obligations', sa.Float(), nullable=False),
    sa.Column('award_count', sa.Integer(), nullable=False),
    sa.Column('top_agency', sa.String(length=200), nullable=True),
    sa.Column('top_agency_pct', sa.Float(), nullable=True),
    sa.Column('agency_concentration', sa.JSON(), nullable=False),
    sa.Column('top_awards', sa.JSON(), nullable=False),
    sa.Column('recompete', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('memos',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('memo_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memos_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('red_team_reports',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('bear_case_markdown', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('unsupported_claims', sa.JSON(), nullable=False),
    sa.Column('missing_evidence', sa.JSON(), nullable=False),
    sa.Column('high_priority_questions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('risk_findings',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('risk_category', sa.String(length=40), nullable=False),
    sa.Column('risk_category_label', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('likelihood', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=20), nullable=True),
    sa.Column('follow_up_question', sa.Text(), nullable=False),
    sa.Column('workstream_owner', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_findings_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('targets',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('rnd_pct', sa.Float(), nullable=True),
    sa.Column('rule_of_40', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('fiscal_year_end', sa.String(length=20), nullable=True),
    sa.Column('data_source', sa.String(length=60), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('financials', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('underwriting_case_versions',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('case_key', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.String(length=32), nullable=True),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("case_key IN ('base', 'upside', 'downside')", name='ck_case_key'),
    sa.CheckConstraint('version > 0', name='ck_case_version_positive'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['underwriting_case_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'case_key', 'version', name='uq_underwriting_case_version')
    )
    with op.batch_alter_table('underwriting_case_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_underwriting_case_versions_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_underwriting_case_workspace_key', ['workspace_id', 'case_key'], unique=False)

    op.create_table('artifact_versions',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('artifact_type', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=32), nullable=True),
    sa.Column('analysis_run_id', sa.String(length=32), nullable=True),
    sa.Column('source_snapshot_ids', sa.JSON(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('file_uri', sa.Text(), nullable=True),
    sa.Column('artifact_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['artifact_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'artifact_type', 'version', name='uq_artifact_type_version')
    )
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_versions_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_versions_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_versions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('deals',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('fund_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_company', sa.String(length=200), nullable=False),
    sa.Column('deal_type', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_actor_id', sa.String(length=200), nullable=True),
    sa.Column('ic_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage IN ('sourcing','screening','initial_review','diligence','ic_review','signing','closed','declined')", name='ck_deals_stage'),
    sa.CheckConstraint("status IN ('active','on_hold','closed','declined')", name='ck_deals_status'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_deals_org_code'),
    sa.UniqueConstraint('workspace_id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index('ix_deals_org_stage', ['organization_id', 'stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_owner_actor_id'), ['owner_actor_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('filing_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=200), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding_id', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_filing_id'), ['filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('sec_filing_comparisons',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('from_filing_id', sa.String(length=32), nullable=False),
    sa.Column('to_filing_id', sa.String(length=32), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_filing_id'], ['filings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_filing_id'], ['filings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sec_filing_comparisons', schema=None) as batch_op:
        batch_op.create_index('ix_sec_filing_comparisons_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sec_filing_comparisons_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('source_snapshots',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_name', sa.String(length=240), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=260), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'source_type', 'source_name', 'version', name='uq_source_snapshot_stream_version')
    )
    with op.batch_alter_table('source_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_snapshots_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_snapshots_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_snapshots_source_kind'), ['source_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_snapshots_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_snapshots_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_snapshots_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('underwriting_case_decisions',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('case_version_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('submitted', 'approved', 'rejected', 'superseded')", name='ck_underwriting_decision'),
    sa.ForeignKeyConstraint(['case_version_id'], ['underwriting_case_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('underwriting_case_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_underwriting_case_decisions_case_version_id'), ['case_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_underwriting_case_decisions_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_underwriting_decision_version_created', ['case_version_id', 'created_at'], unique=False)

    op.create_table('canonical_financial_facts',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('account_mapping_id', sa.String(length=32), nullable=True),
    sa.Column('statement', sa.String(length=30), nullable=False),
    sa.Column('raw_account', sa.String(length=240), nullable=False),
    sa.Column('raw_account_normalized', sa.String(length=240), nullable=False),
    sa.Column('canonical_account', sa.String(length=120), nullable=True),
    sa.Column('mapping_state', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('raw_value', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('scale_factor', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source_sheet', sa.String(length=160), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('source_locator', sa.Text(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_mapping_id'], ['account_mappings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_snapshot_id', 'row_hash', name='uq_fact_snapshot_row_hash')
    )
    with op.batch_alter_table('canonical_financial_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canonical_financial_facts_canonical_account'), ['canonical_account'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_financial_facts_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_financial_facts_raw_account_normalized'), ['raw_account_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_financial_facts_source_snapshot_id'), ['source_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_financial_facts_statement'), ['statement'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_financial_facts_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_financial_facts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('cited_qa_runs',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('retrieval_metadata', sa.JSON(), nullable=False),
    sa.Column('answer_hash', sa.String(length=64), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint("status IN ('answered','abstained')", name='ck_cited_qa_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cited_qa_runs', schema=None) as batch_op:
        batch_op.create_index('ix_cited_qa_runs_deal_created', ['deal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cited_qa_runs_deal_id'), ['deal_id'], unique=False)

    op.create_table('data_room_documents',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('logical_document_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_document_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('filename', sa.String(length=240), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('extension', sa.String(length=12), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('raw_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint('byte_size > 0', name='ck_data_room_document_nonempty'),
    sa.CheckConstraint('version >= 1', name='ck_data_room_document_version'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_document_id'], ['data_room_documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'logical_document_id', 'version', name='uq_data_room_document_version')
    )
    with op.batch_alter_table('data_room_documents', schema=None) as batch_op:
        batch_op.create_index('ix_data_room_documents_deal_created', ['deal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_room_documents_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index('ix_data_room_documents_deal_logical', ['deal_id', 'logical_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_room_documents_logical_document_id'), ['logical_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_room_documents_sha256'), ['sha256'], unique=False)

    op.create_table('deal_ledger_entries',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('root_entry_id', sa.String(length=32), nullable=True),
    sa.Column('supersedes_entry_id', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('owner_actor_id', sa.String(length=200), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('related_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entry_type IN ('thesis','issue','risk','decision')", name='ck_deal_ledger_type'),
    sa.CheckConstraint("severity IN ('low','medium','high','critical')", name='ck_deal_ledger_severity'),
    sa.CheckConstraint("status IN ('open','validated','mitigated','accepted','rejected','resolved','superseded')", name='ck_deal_ledger_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_entry_id'], ['deal_ledger_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_deal_ledger_deal_type_status', ['deal_id', 'entry_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_ledger_entries_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_ledger_entries_root_entry_id'), ['root_entry_id'], unique=False)

    op.create_table('deal_stage_gates',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('resolved_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','satisfied','waived')", name='ck_deal_stage_gates_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'stage', 'code', name='uq_deal_gate_stage_code')
    )
    with op.batch_alter_table('deal_stage_gates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_stage_gates_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index('ix_deal_stage_gates_deal_stage', ['deal_id', 'stage'], unique=False)

    op.create_table('deal_stage_transitions',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=30), nullable=False),
    sa.Column('to_stage', sa.String(length=30), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'sequence', name='uq_deal_transition_sequence')
    )
    with op.batch_alter_table('deal_stage_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_stage_transitions_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index('ix_deal_transitions_deal_created', ['deal_id', 'created_at'], unique=False)

    op.create_table('deal_team_members',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('deal_lead','investment_partner','principal','associate','operating_partner','finance','legal','advisor','observer')", name='ck_deal_team_role'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'actor_id', name='uq_deal_team_actor')
    )
    with op.batch_alter_table('deal_team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_team_members_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_team_members_deal_id'), ['deal_id'], unique=False)

    op.create_table('deal_workstreams',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('lead_actor_id', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('not_started','in_progress','blocked','complete','waived')", name='ck_deal_workstreams_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'slug', name='uq_deal_workstream_slug')
    )
    with op.batch_alter_table('deal_workstreams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_workstreams_deal_id'), ['deal_id'], unique=False)

    op.create_table('financial_reconciliations',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('assets', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('liabilities_and_equity', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('difference', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('tolerance', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_snapshot_id', 'period_end', name='uq_reconciliation_snapshot_period')
    )
    with op.batch_alter_table('financial_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_reconciliations_source_snapshot_id'), ['source_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reconciliations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ic_packets',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_packet_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scenario_snapshot', sa.JSON(), nullable=False),
    sa.Column('model_snapshot', sa.JSON(), nullable=False),
    sa.Column('evidence_manifest', sa.JSON(), nullable=False),
    sa.Column('thesis_snapshot', sa.JSON(), nullable=False),
    sa.Column('risk_snapshot', sa.JSON(), nullable=False),
    sa.Column('decision_request', sa.JSON(), nullable=False),
    sa.Column('readiness_snapshot', sa.JSON(), nullable=False),
    sa.Column('ready_for_submission', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('submitted_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','submitted','in_review','approved','conditional','deferred','declined','superseded')", name='ck_ic_packets_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_packet_id'], ['ic_packets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'content_hash', name='uq_ic_packet_content_hash'),
    sa.UniqueConstraint('deal_id', 'version', name='uq_ic_packet_version')
    )
    with op.batch_alter_table('ic_packets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ic_packets_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index('ix_ic_packets_deal_version', ['deal_id', 'version'], unique=False)

    op.create_table('intelligence_evaluations',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('cases', sa.JSON(), nullable=False),
    sa.Column('qa_run_ids', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intelligence_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_intelligence_evaluations_deal_created', ['deal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_evaluations_deal_id'), ['deal_id'], unique=False)

    op.create_table('qoe_adjustments',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('bridge_layer', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_run_rate', sa.Boolean(), nullable=False),
    sa.Column('is_cash', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('evidence_ref', sa.String(length=40), nullable=True),
    sa.Column('source_locator', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'dedupe_key', name='uq_qoe_adjustment_dedupe')
    )
    with op.batch_alter_table('qoe_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qoe_adjustments_bridge_layer'), ['bridge_layer'], unique=False)
        batch_op.create_index(batch_op.f('ix_qoe_adjustments_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_qoe_adjustments_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qoe_adjustments_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workflow_audit_events',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('deal_id', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('actor_display_name', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_audit_deal_created', ['deal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_audit_events_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_audit_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_workflow_audit_org_created', ['organization_id', 'created_at'], unique=False)

    op.create_table('data_room_chunks',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('locator_type', sa.String(length=20), nullable=False),
    sa.Column('locator', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['data_room_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_data_room_chunk_ordinal')
    )
    with op.batch_alter_table('data_room_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_data_room_chunks_deal_document', ['deal_id', 'document_id', 'ordinal'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_room_chunks_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_room_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('deal_milestones',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('workstream_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('owner_actor_id', sa.String(length=200), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('not_started','in_progress','blocked','complete','cancelled')", name='ck_deal_milestones_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['deal_workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_milestones', schema=None) as batch_op:
        batch_op.create_index('ix_deal_milestones_deal_due', ['deal_id', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_milestones_deal_id'), ['deal_id'], unique=False)

    op.create_table('diligence_requests',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('workstream_id', sa.String(length=32), nullable=True),
    sa.Column('request_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('owner_actor_id', sa.String(length=200), nullable=True),
    sa.Column('respondent_actor_id', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('low','medium','high','critical')", name='ck_diligence_requests_priority'),
    sa.CheckConstraint("status IN ('draft','requested','responded','under_review','accepted','rejected','closed')", name='ck_diligence_requests_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['deal_workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'request_number', name='uq_diligence_request_number')
    )
    with op.batch_alter_table('diligence_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diligence_requests_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index('ix_diligence_requests_deal_status_due', ['deal_id', 'status', 'due_date'], unique=False)

    op.create_table('document_comparisons',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('from_document_id', sa.String(length=32), nullable=False),
    sa.Column('to_document_id', sa.String(length=32), nullable=False),
    sa.Column('comparison_type', sa.String(length=20), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint("comparison_type IN ('change','contradiction')", name='ck_document_comparison_type'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_document_id'], ['data_room_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_document_id'], ['data_room_documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_comparisons', schema=None) as batch_op:
        batch_op.create_index('ix_document_comparisons_deal_created', ['deal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comparisons_deal_id'), ['deal_id'], unique=False)

    op.create_table('financial_import_exceptions',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('fact_id', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['canonical_financial_facts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_import_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_import_exceptions_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_import_exceptions_source_snapshot_id'), ['source_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_import_exceptions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ic_comments',
    sa.Column('packet_id', sa.String(length=32), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=32), nullable=True),
    sa.Column('section_path', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_actor_id', sa.String(length=200), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('resolved_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open','resolved')", name='ck_ic_comments_status'),
    sa.ForeignKeyConstraint(['packet_id'], ['ic_packets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['ic_comments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ic_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ic_comments_packet_id'), ['packet_id'], unique=False)
        batch_op.create_index('ix_ic_comments_packet_status', ['packet_id', 'status'], unique=False)

    op.create_table('ic_decisions',
    sa.Column('packet_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('decided_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('meeting_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint("decision IN ('approve','conditional','defer','decline')", name='ck_ic_decisions_value'),
    sa.ForeignKeyConstraint(['packet_id'], ['ic_packets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('packet_id', 'sequence', name='uq_ic_decision_sequence')
    )
    with op.batch_alter_table('ic_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ic_decisions_packet_id'), ['packet_id'], unique=False)

    op.create_table('ic_packet_exports',
    sa.Column('packet_id', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('requested_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint("format IN ('pdf','docx','xlsx','json')", name='ck_ic_exports_format'),
    sa.ForeignKeyConstraint(['packet_id'], ['ic_packets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ic_packet_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ic_packet_exports_manifest_hash'), ['manifest_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ic_packet_exports_packet_id'), ['packet_id'], unique=False)

    op.create_table('conditions_to_close',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('packet_id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_actor_id', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('resolved_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open','satisfied','waived')", name='ck_conditions_to_close_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['ic_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packet_id'], ['ic_packets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conditions_to_close', schema=None) as batch_op:
        batch_op.create_index('ix_conditions_deal_status_due', ['deal_id', 'status', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_conditions_to_close_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conditions_to_close_packet_id'), ['packet_id'], unique=False)

    op.create_table('deal_tasks',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('workstream_id', sa.String(length=32), nullable=True),
    sa.Column('milestone_id', sa.String(length=32), nullable=True),
    sa.Column('parent_task_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_actor_id', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('dependency_task_ids', sa.JSON(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('low','medium','high','critical')", name='ck_deal_tasks_priority'),
    sa.CheckConstraint("status IN ('not_started','in_progress','blocked','complete','cancelled')", name='ck_deal_tasks_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['deal_milestones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['deal_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workstream_id'], ['deal_workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_tasks_assignee_actor_id'), ['assignee_actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_tasks_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index('ix_deal_tasks_deal_status_due', ['deal_id', 'status', 'due_date'], unique=False)

    op.create_table('diligence_responses',
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('responded_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['diligence_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'sequence', name='uq_diligence_response_sequence')
    )
    with op.batch_alter_table('diligence_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diligence_responses_request_id'), ['request_id'], unique=False)

    op.create_table('structured_claims',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('logical_claim_id', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('supersedes_claim_id', sa.String(length=32), nullable=True),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=False),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_locator', sa.JSON(), nullable=False),
    sa.Column('source_span', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('extraction_version', sa.String(length=40), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint("category IN ('debt_term','customer','contract','kpi','qoe_candidate')", name='ck_structured_claim_category'),
    sa.CheckConstraint("review_status IN ('unreviewed','approved','rejected')", name='ck_structured_claim_review_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_claim_confidence'),
    sa.CheckConstraint('revision >= 1', name='ck_structured_claim_revision'),
    sa.ForeignKeyConstraint(['chunk_id'], ['data_room_chunks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['data_room_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_claim_id'], ['structured_claims.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_claim_id', 'revision', name='uq_structured_claim_revision')
    )
    with op.batch_alter_table('structured_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_structured_claims_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index('ix_structured_claims_deal_status', ['deal_id', 'review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_claims_logical_claim_id'), ['logical_claim_id'], unique=False)
        batch_op.create_index('ix_structured_claims_logical_revision', ['logical_claim_id', 'revision'], unique=False)

    op.create_table('claim_review_events',
    sa.Column('deal_id', sa.String(length=32), nullable=False),
    sa.Column('logical_claim_id', sa.String(length=32), nullable=False),
    sa.Column('from_claim_id', sa.String(length=32), nullable=False),
    sa.Column('to_claim_id', sa.String(length=32), nullable=False),
    sa.Column('from_revision', sa.Integer(), nullable=False),
    sa.Column('to_revision', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('prior_status', sa.String(length=20), nullable=False),
    sa.Column('resulting_status', sa.String(length=20), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('reviewer_actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.CheckConstraint("action IN ('approve','reject','edit')", name='ck_claim_review_action'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_claim_id'], ['structured_claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_claim_id'], ['structured_claims.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_claim_id', 'to_revision', name='uq_claim_review_to_revision')
    )
    with op.batch_alter_table('claim_review_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_review_events_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_review_events_logical_claim_id'), ['logical_claim_id'], unique=False)
        batch_op.create_index('ix_claim_reviews_logical_created', ['logical_claim_id', 'created_at'], unique=False)

    op.create_table('diligence_attachments',
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('response_id', sa.String(length=32), nullable=True),
    sa.Column('artifact_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_actor_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['diligence_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['diligence_responses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'source_hash', 'version', name='uq_diligence_attachment_version')
    )
    with op.batch_alter_table('diligence_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diligence_attachments_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diligence_attachments_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diligence_attachments_source_hash'), ['source_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diligence_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diligence_attachments_source_hash'))
        batch_op.drop_index(batch_op.f('ix_diligence_attachments_request_id'))
        batch_op.drop_index(batch_op.f('ix_diligence_attachments_artifact_id'))

    op.drop_table('diligence_attachments')
    with op.batch_alter_table('claim_review_events', schema=None) as batch_op:
        batch_op.drop_index('ix_claim_reviews_logical_created')
        batch_op.drop_index(batch_op.f('ix_claim_review_events_logical_claim_id'))
        batch_op.drop_index(batch_op.f('ix_claim_review_events_deal_id'))

    op.drop_table('claim_review_events')
    with op.batch_alter_table('structured_claims', schema=None) as batch_op:
        batch_op.drop_index('ix_structured_claims_logical_revision')
        batch_op.drop_index(batch_op.f('ix_structured_claims_logical_claim_id'))
        batch_op.drop_index('ix_structured_claims_deal_status')
        batch_op.drop_index(batch_op.f('ix_structured_claims_deal_id'))

    op.drop_table('structured_claims')
    with op.batch_alter_table('diligence_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diligence_responses_request_id'))

    op.drop_table('diligence_responses')
    with op.batch_alter_table('deal_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_deal_tasks_deal_status_due')
        batch_op.drop_index(batch_op.f('ix_deal_tasks_deal_id'))
        batch_op.drop_index(batch_op.f('ix_deal_tasks_assignee_actor_id'))

    op.drop_table('deal_tasks')
    with op.batch_alter_table('conditions_to_close', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conditions_to_close_packet_id'))
        batch_op.drop_index(batch_op.f('ix_conditions_to_close_deal_id'))
        batch_op.drop_index('ix_conditions_deal_status_due')

    op.drop_table('conditions_to_close')
    with op.batch_alter_table('ic_packet_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ic_packet_exports_packet_id'))
        batch_op.drop_index(batch_op.f('ix_ic_packet_exports_manifest_hash'))

    op.drop_table('ic_packet_exports')
    with op.batch_alter_table('ic_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ic_decisions_packet_id'))

    op.drop_table('ic_decisions')
    with op.batch_alter_table('ic_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_ic_comments_packet_status')
        batch_op.drop_index(batch_op.f('ix_ic_comments_packet_id'))

    op.drop_table('ic_comments')
    with op.batch_alter_table('financial_import_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_import_exceptions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_financial_import_exceptions_source_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_financial_import_exceptions_code'))

    op.drop_table('financial_import_exceptions')
    with op.batch_alter_table('document_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_comparisons_deal_id'))
        batch_op.drop_index('ix_document_comparisons_deal_created')

    op.drop_table('document_comparisons')
    with op.batch_alter_table('diligence_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_diligence_requests_deal_status_due')
        batch_op.drop_index(batch_op.f('ix_diligence_requests_deal_id'))

    op.drop_table('diligence_requests')
    with op.batch_alter_table('deal_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_milestones_deal_id'))
        batch_op.drop_index('ix_deal_milestones_deal_due')

    op.drop_table('deal_milestones')
    with op.batch_alter_table('data_room_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_room_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_data_room_chunks_deal_id'))
        batch_op.drop_index('ix_data_room_chunks_deal_document')

    op.drop_table('data_room_chunks')
    with op.batch_alter_table('workflow_audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_workflow_audit_org_created')
        batch_op.drop_index(batch_op.f('ix_workflow_audit_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_audit_events_deal_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_audit_events_action'))
        batch_op.drop_index('ix_workflow_audit_deal_created')

    op.drop_table('workflow_audit_events')
    with op.batch_alter_table('qoe_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qoe_adjustments_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_qoe_adjustments_target_id'))
        batch_op.drop_index(batch_op.f('ix_qoe_adjustments_period_end'))
        batch_op.drop_index(batch_op.f('ix_qoe_adjustments_bridge_layer'))

    op.drop_table('qoe_adjustments')
    with op.batch_alter_table('intelligence_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_evaluations_deal_id'))
        batch_op.drop_index('ix_intelligence_evaluations_deal_created')

    op.drop_table('intelligence_evaluations')
    with op.batch_alter_table('ic_packets', schema=None) as batch_op:
        batch_op.drop_index('ix_ic_packets_deal_version')
        batch_op.drop_index(batch_op.f('ix_ic_packets_deal_id'))

    op.drop_table('ic_packets')
    with op.batch_alter_table('financial_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_reconciliations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_financial_reconciliations_source_snapshot_id'))

    op.drop_table('financial_reconciliations')
    with op.batch_alter_table('deal_workstreams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_workstreams_deal_id'))

    op.drop_table('deal_workstreams')
    with op.batch_alter_table('deal_team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_team_members_deal_id'))
        batch_op.drop_index(batch_op.f('ix_deal_team_members_actor_id'))

    op.drop_table('deal_team_members')
    with op.batch_alter_table('deal_stage_transitions', schema=None) as batch_op:
        batch_op.drop_index('ix_deal_transitions_deal_created')
        batch_op.drop_index(batch_op.f('ix_deal_stage_transitions_deal_id'))

    op.drop_table('deal_stage_transitions')
    with op.batch_alter_table('deal_stage_gates', schema=None) as batch_op:
        batch_op.drop_index('ix_deal_stage_gates_deal_stage')
        batch_op.drop_index(batch_op.f('ix_deal_stage_gates_deal_id'))

    op.drop_table('deal_stage_gates')
    with op.batch_alter_table('deal_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_ledger_entries_root_entry_id'))
        batch_op.drop_index(batch_op.f('ix_deal_ledger_entries_deal_id'))
        batch_op.drop_index('ix_deal_ledger_deal_type_status')

    op.drop_table('deal_ledger_entries')
    with op.batch_alter_table('data_room_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_room_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_data_room_documents_logical_document_id'))
        batch_op.drop_index('ix_data_room_documents_deal_logical')
        batch_op.drop_index(batch_op.f('ix_data_room_documents_deal_id'))
        batch_op.drop_index('ix_data_room_documents_deal_created')

    op.drop_table('data_room_documents')
    with op.batch_alter_table('cited_qa_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cited_qa_runs_deal_id'))
        batch_op.drop_index('ix_cited_qa_runs_deal_created')

    op.drop_table('cited_qa_runs')
    with op.batch_alter_table('canonical_financial_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_financial_facts_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_canonical_financial_facts_target_id'))
        batch_op.drop_index(batch_op.f('ix_canonical_financial_facts_statement'))
        batch_op.drop_index(batch_op.f('ix_canonical_financial_facts_source_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_canonical_financial_facts_raw_account_normalized'))
        batch_op.drop_index(batch_op.f('ix_canonical_financial_facts_period_end'))
        batch_op.drop_index(batch_op.f('ix_canonical_financial_facts_canonical_account'))

    op.drop_table('canonical_financial_facts')
    with op.batch_alter_table('underwriting_case_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_underwriting_decision_version_created')
        batch_op.drop_index(batch_op.f('ix_underwriting_case_decisions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_underwriting_case_decisions_case_version_id'))

    op.drop_table('underwriting_case_decisions')
    with op.batch_alter_table('source_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_snapshots_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_source_snapshots_target_id'))
        batch_op.drop_index(batch_op.f('ix_source_snapshots_source_type'))
        batch_op.drop_index(batch_op.f('ix_source_snapshots_source_kind'))
        batch_op.drop_index(batch_op.f('ix_source_snapshots_input_hash'))
        batch_op.drop_index(batch_op.f('ix_source_snapshots_content_hash'))

    op.drop_table('source_snapshots')
    with op.batch_alter_table('sec_filing_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sec_filing_comparisons_workspace_id'))
        batch_op.drop_index('ix_sec_filing_comparisons_workspace_created')

    op.drop_table('sec_filing_comparisons')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_filing_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_owner_actor_id'))
        batch_op.drop_index(batch_op.f('ix_deals_organization_id'))
        batch_op.drop_index('ix_deals_org_stage')
        batch_op.drop_index(batch_op.f('ix_deals_fund_id'))

    op.drop_table('deals')
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_versions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_versions_input_hash'))
        batch_op.drop_index(batch_op.f('ix_artifact_versions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_artifact_versions_artifact_type'))

    op.drop_table('artifact_versions')
    with op.batch_alter_table('underwriting_case_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_underwriting_case_workspace_key')
        batch_op.drop_index(batch_op.f('ix_underwriting_case_versions_workspace_id'))

    op.drop_table('underwriting_case_versions')
    op.drop_table('targets')
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_findings_workspace_id'))

    op.drop_table('risk_findings')
    op.drop_table('red_team_reports')
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memos_workspace_id'))

    op.drop_table('memos')
    op.drop_table('govcon_profiles')
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funds_organization_id'))

    op.drop_table('funds')
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filings_workspace_id'))

    op.drop_table('filings')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_ref'))

    op.drop_table('evidence')
    with op.batch_alter_table('diligence_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diligence_questions_workspace_id'))

    op.drop_table('diligence_questions')
    op.drop_table('diligence_plans')
    with op.batch_alter_table('comparable_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparable_companies_workspace_id'))

    op.drop_table('comparable_companies')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_workspace_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_run_type'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_input_hash'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_content_hash'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('account_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_mappings_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_account_mappings_raw_account_normalized'))
        batch_op.drop_index(batch_op.f('ix_account_mappings_canonical_account'))

    op.drop_table('account_mappings')
    op.drop_table('workspaces')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
